# Generated by Django 6.0.5 on 2026-06-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_type',
            field=models.CharField(choices=[('flash_sale', 'Flash Sale Only'), ('todays_for_you', 'Todays For You Only'), ('both', 'Both Sections')], default='todays_for_you', max_length=20),
        ),
    ]
