# Generated by Django 6.0.5 on 2026-06-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_sale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_count',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
