# Generated by Django 6.0.5 on 2026-06-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_usercategorypreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_vector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
