# Generated by Django 6.0.5 on 2026-06-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_image_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_threshold', models.FloatField(default=0.68, help_text='Minimum cosine similarity score (0.0 to 1.0) required for a visual match. Default is 0.68.')),
                ('is_active', models.BooleanField(default=True, help_text='Enable this row configuration to control the live search matching threshold parameters.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Search Configuration',
                'verbose_name_plural': 'Search Configurations',
            },
        ),
    ]
